vector-im/element-call

.vscode/settings.json

I hope you don't mind the PR :sweat_smile:

Add a few things to VS Code settings

---

package-lock.json
package.json
src/DevTools.jsx

Fixes https://github.com/vector-im/matrix-video-chat/issues/3

Make devtools resizable

---

src/ConferenceCallManager.js
src/ConferenceCallManagerHooks.js
src/Room.jsx
src/VideoGrid.jsx
src/VideoGrid.module.css

Add mute indicators

---

src/App.jsx
src/ConferenceCallManager.js
src/ConferenceCallManagerHooks.js
src/Home.jsx
src/Input.jsx
src/Input.module.css
src/LoginPage.jsx
src/RegisterPage.jsx
src/Room.jsx
src/VideoGrid.jsx
src/icons/Check.svg

Closes #10 
Requires a [small change to Synapse](https://github.com/robertlong/synapse/tree/robertlong/full-mesh-voip) for guest member state event permissions.

Add guest access for rooms

---

Dockerfile
scripts/default.conf

Fix docker build

---

src/settings/rageshake.js

Reverts vector-im/matrix-video-chat#206

Revert "Rename groupcall.txt -> groupcall.json."

---

vite.config.js

Enable source maps for debugging in production

Enable source-maps

---

src/input/Toggle.jsx

Just use isSelected directly rather than makking the button have its
own state. Also, the isPressed from useToggleButton looks like its
whether the user has the mouse button down on it or not rather than
whether the toggle switch is on, which was making the state wrong.

Fix toggle button toggling

---

.vscode/settings.json

Although this will only work with the extension installed

Set formatter to prettier

---

package.json
src/auth/useInteractiveLogin.js
src/auth/useInteractiveRegistration.js
src/home/useGroupCallRooms.js
src/room/useLoadGroupCall.js
src/room/usePTT.js
src/settings/submit-rageshake.js

Various hooks either missing dependencies or with extra ones.
Two remaining errors are from the recapcta code where I can't
work out if the extra dependency is intentional or not.

Fix lint errors

---

src/video-grid/VideoGrid.jsx

https://user-images.githubusercontent.com/48614497/168914181-6cdab1ff-a9f9-407a-82fb-7697b5b71dd0.mp4
Closes https://github.com/vector-im/element-call/issues/254.

Make local video in 1:1 calls draggable

---

src/Avatar.tsx
src/Facepile.jsx
src/Header.jsx
src/home/useGroupCallRooms.js
src/profile/useProfile.js
src/room/GroupCallView.jsx
src/room/InCallView.jsx
src/room/LobbyView.jsx
src/room/PTTButton.tsx
src/room/PTTCallView.tsx
src/room/VideoPreview.jsx
src/room/useRoomAvatar.ts

Demo showing the various places they can show up:
https://user-images.githubusercontent.com/48614497/169169193-139c369f-21d0-4b03-a094-2a0202c373b1.mp4
Closes https://github.com/vector-im/element-call/issues/50

Display room avatars

---

src/home/UnauthenticatedView.jsx

This was another thing that could cause https://github.com/vector-im/element-call/issues/286

Fix joining an existing room from UnregisteredView

---

src/video-grid/useMediaStream.js

Closes https://github.com/vector-im/element-call/issues/304

Prevent video elements from being mistakenly muted/unmuted

---

src/auth/RegisterPage.jsx

Closes https://github.com/vector-im/element-call/issues/235

Handle rate limits when upgrading from a guest account

---

src/input/Input.jsx
src/input/Input.module.css
src/settings/SettingsModal.jsx

Tweak spatial audio copy

---

package.json
yarn.lock

Fixes https://github.com/vector-im/element-call/issues/267

Update js-sdk for chrome audio renderer hang fix

---

src/profile/useProfile.ts

(For a curious definition of 'fix')

Fix js-sdk imports to be from src

---

src/room/PTTButton.module.css
src/room/PTTCallView.module.css
src/room/PTTCallView.tsx

Closes https://github.com/vector-im/element-call/issues/432

Adapt walkie-talkie layout to hide controls at small sizes

---

src/room/GroupCallView.jsx
src/room/LobbyView.jsx

Fixes https://github.com/vector-im/element-call/issues/443

Remove the 'Take Me Home' link in embed mode

---

package.json
src/ClientContext.tsx
src/button/Button.tsx
yarn.lock

Fixes https://github.com/vector-im/element-call/issues/456 as
the various react libraries had got out of sync (also we were well
overdue a dependency update).

yarn upgrade

---

src/room/GroupCallView.jsx

Fixes https://github.com/vector-im/element-call/issues/460

Bypass lobby in embedded mode

---

package.json
src/room/useGroupCall.ts
yarn.lock

Requires https://github.com/vector-im/element-call/pull/468
Requires https://github.com/matrix-org/matrix-js-sdk/pull/2530

Add support for audio sharing

---

src/room/InCallView.tsx
src/video-grid/VideoTile.jsx
src/video-grid/VideoTileContainer.jsx
src/video-grid/useCallFeed.js

Fixes https://github.com/vector-im/element-call/issues/282

Show name in 1:1 calls

---

src/video-grid/VideoTileSettingsModal.module.css

Fixes https://github.com/vector-im/element-call/issues/497

Fix the look of volume slider on Firefox

---

src/Facepile.tsx
src/Header.tsx
src/IncompatibleVersionModal.tsx
src/home/CallList.tsx
src/home/RegisteredView.tsx
src/home/useGroupCallRooms.ts
src/profile/ProfileModal.tsx
src/room/CallEndedView.tsx
src/room/GroupCallInspector.tsx
src/room/GroupCallLoader.tsx
src/room/GroupCallView.tsx
src/room/InCallView.tsx
src/room/PTTCallView.tsx
src/settings/submit-rageshake.ts
src/settings/useMediaHandler.tsx
src/video-grid/VideoTileContainer.tsx
src/video-grid/useCallFeed.ts
src/video-grid/useRoomMemberName.ts

Remove top level matrix-js-sdk imports

---

src/ClientContext.tsx

To prevent sessions from piling up quite as much

Log out lost sessions

---

src/room/FeedbackModal.tsx

Fixes https://github.com/vector-im/element-call/issues/515

Fix the Feedback modal not being closable

---

src/room/InCallView.tsx
src/video-grid/AudioContainer.tsx
src/video-grid/VideoTileContainer.jsx
src/video-grid/VideoTileContainer.tsx
src/video-grid/useAudioOutputDevice.ts
src/video-grid/useMediaStream.ts

Fixes https://github.com/vector-im/element-call/issues/509

Fix audio during full-screening

---

src/Header.tsx
src/home/RegisteredView.tsx
src/home/UnauthenticatedView.tsx
src/matrix-utils.ts
src/room/useLoadGroupCall.ts

I also converted UnauthenticatedView to TypeScript for good measure, since TypeScript would've caught this problem.
Closes https://github.com/vector-im/element-call/issues/534

Fix the call type selector

---

package.json
src/video-grid/useCallFeed.ts
src/video-grid/useFullscreen.tsx

Requires https://github.com/matrix-org/matrix-js-sdk/pull/2604

Handle screen-sharing feed ending during full-screening

---

src/room/FeedbackModal.tsx

Fixes https://github.com/vector-im/element-call/issues/550

Fix 'submit debug logs' checkbox in the rageshake form

---

package.json
src/ClientContext.tsx
src/LazyEventEmitter.ts
src/matrix-utils.ts
src/room/GroupCallView.tsx
src/room/InCallView.tsx
src/room/LobbyView.tsx
src/room/PTTCallView.tsx
src/room/RoomPage.tsx
src/room/useRoomParams.ts
src/widget.ts
yarn.lock

See the individual commits for details
Depends on https://github.com/matrix-org/matrix-js-sdk/pull/2657

Prepare for integration into Element Web

---

src/ClientContext.tsx

fix logout

---

package.json
yarn.lock

For https://github.com/matrix-org/matrix-js-sdk/pull/2662

Bump js-sdk dependency

---

package.json
yarn.lock

For https://github.com/matrix-org/matrix-js-sdk/pull/2667

Update js-sdk for exception fix

---

src/room/InCallView.module.css
src/room/InCallView.tsx
src/video-grid/VideoGrid.stories.tsx
src/video-grid/VideoTile.module.css
src/video-grid/VideoTile.tsx
src/video-grid/VideoTileContainer.tsx

The purpose of this is to make Element Call look nice when shown in a picture-in-picture view inside Element Web:

Maximise the active speaker when the window is small

---

package.json
yarn.lock

To get https://github.com/matrix-org/matrix-js-sdk/pull/2670

Update matrix-js-sdk and matrix-widget-api

---

src/video-grid/VideoTile.tsx

Closes https://github.com/vector-im/element-call/issues/555

Don't allow the user to fullscreen their own screenshare feed

---

src/room/useLoadGroupCall.ts

Wait for the client to start syncing before we attempt to join a room.
Fixes https://github.com/vector-im/element-call/issues/600 (detailed bug analysis is also in that issue).

Fix another cause of split-brain rooms

---

src/room/GroupCallView.tsx

Fixes https://github.com/vector-im/element-call/issues/596

Fix bug causing mic/webcam to remain open after call

---

src/video-grid/VideoTile.module.css

instead of getting letterboxed.

Let the maximized video feed fill the window

---

src/UrlParams.ts
src/widget.ts

The client just didn't have a homeserver URL to perform media queries against.

Make avatars work in matryoshka mode

---

src/room/useGroupCall.ts
src/widget.ts

Requires https://github.com/matrix-org/matrix-react-sdk/pull/9476

Make Element Call screensharing work on desktop

---

src/video-grid/VideoGrid.tsx

Closes https://github.com/vector-im/element-call/issues/646

Re-enable focusing tiles in 1:1 calls

---

.github/workflows/test.yaml
babel.config.cjs
package.json
src/App.tsx
src/matrix-utils.ts
test/home/CallList-test.tsx
test/mocks/workerMock.ts
tsconfig.json
yarn.lock

Fixes https://github.com/vector-im/element-call/issues/636

Set up unit testing

---

src/main.tsx

Closes https://github.com/vector-im/element-call/issues/671

Show an error when the browser does not support WebRTC

---

.github/workflows/triage-incoming.yaml

Not entirely sure if this will work, mainly because the access token might not be there

Add basic triage automation

---

.github/workflows/triage-incoming.yaml

The 'PR_' ID format appears to be deprecated.

Attempt to fix triage automation

---

src/matrix-utils.ts

Closes https://github.com/vector-im/element-call/issues/570

Fix blurry avatars

---

src/room/InCallView.tsx

Closes https://github.com/vector-im/element-call/issues/713

Fix a crash when someone leaves while screensharing

---

src/IncompatibleVersionModal.tsx
src/Modal.tsx
src/home/JoinExistingCallModal.tsx
src/video-grid/VideoTileSettingsModal.tsx

It just errored as we didn't pass onClose through to the modal

Fix close button on join call modal

---

src/video-grid/VideoTileContainer.tsx

Closes https://github.com/vector-im/element-call/issues/733

Disable spatial audio for the maximized speaker

---

src/video-grid/VideoTileContainer.tsx
src/video-grid/useMediaStream.ts

And potentially fix it, by recreating the source node when the stream changes.

Add logs to debug missing spatial audio

---

README.md
package.json
yarn.lock

Requires https://github.com/matrix-org/matrix-js-sdk/pull/2860

Switch to the develop branch of matrix-js-sdk

---

.env.example
.gitignore
README.md
sample.config.json
src/config/Config.ts
src/config/ConfigOptions.ts

Closes https://github.com/vector-im/element-call/issues/730

Improve config documentation and setup

---

src/settings/submit-rageshake.ts

Fixes https://github.com/vector-im/element-call/issues/754

Put rageshake request ID in title of debug log submission

---

package.json
src/room/useGroupCall.ts
yarn.lock

Requires https://github.com/matrix-org/matrix-js-sdk/pull/2941

Don't expose `calls` on `GroupCall`

---

src/Header.module.css
src/ListBox.module.css
src/Menu.module.css
src/Modal.module.css
src/Tooltip.module.css
src/UrlParams.ts
src/UserMenu.module.css
src/auth/LoginPage.module.css
src/button/Button.module.css
src/index.css
src/initializer.tsx
src/input/Input.module.css
src/input/SelectInput.module.css
src/room/GroupCallInspector.module.css
src/room/LobbyView.module.css
src/room/PTTCallView.module.css
src/typography/Typography.module.css
src/video-grid/VideoTile.module.css
test/initializer-test.ts

For https://github.com/vector-im/element-web/issues/23661
This was also a good chance to switch to the semantic font size names used in Compound.

Add URL params to control fonts

---

src/room/InCallView.tsx

This is to prepare for upcoming design changes to the picture-in-picture view in Element Web.

Hide controls completely in picture-in-picture view

---

.github/workflows/build.yaml
.github/workflows/netlify-main.yaml
.github/workflows/netlify-pr.yaml
config/element_io_preview.json

Using workflow from element-web

Add deploy previews

---

.github/workflows/netlify-pr.yaml

No harm in doing this - just as easy to override config in the code itself.

Use config from the branch we built on PR previews

---

.github/workflows/netlify-main.yaml

Add conditional on head_repo on Netlify main GHA job

---

package.json
src/room/InCallView.tsx
src/video-grid/VideoTileContainer.tsx
yarn.lock

Requires https://github.com/matrix-org/matrix-js-sdk/pull/3047

Add proper (un)subscribe logic

---

src/room/GroupCallView.tsx
src/room/InCallView.tsx
src/room/useGroupCall.ts
src/useCallViewKeyboardShortcuts.ts
src/useKeyboardShortcuts.ts

Fixes: https://github.com/vector-im/element-call/issues/771

Disable keyboard shortcuts when feedback modal is open

---

package.json
src/settings/rageshake.ts

First commit does a bit of cleanup & refactoring. Second commit makes the actual change - more detail in commit messages. Also renames the logger member so it doesn't collide with the logger import.

Change rageshake to save much more regularly

---

src/room/PTTButton.tsx

We called the 'unhold' function even if the button wasn't held which probably will have been generating unmute events even when we weren't muted.
Also use separate handlers for events so we can have specific log lines (and also see where the event comes from when caught in the debugger).

Avoid duplicate PTT button 'unhold' events

---

src/PosthogAnalytics.ts
src/initializer.tsx

Make it less confusing to us when the keys are not set in the config

Inform that the user that config keys are missing

---

src/home/RegisteredView.tsx
src/home/UnauthenticatedView.tsx
src/matrix-utils.ts

Check explicitly to see if the room name that's enetered into the box looks like a room alias and if so, do the sensible thing.
Fixes https://github.com/vector-im/element-call/issues/852

Behave sensibly if a full room alias is entered

---

README.md

Update (fix typo) README.md

---

src/otel/otel.ts

Always enable OpenTelemetry, but conditionally enable the OTLP exporter, as per comment.
Fixes https://github.com/vector-im/element-call/issues/987

Allow different OpenTelemetry collectors to be enabled/disabled

---

package.json
src/otel/OTelGroupCallMembership.ts
yarn.lock

We want the summary report for the entire call as a percentage metric.
We want the stats for each individual connection. 
That's why I created own OTel Span for summary report.

separate summary report from stats report

---

src/analytics/OtelPosthogExporter.ts

Send the connection media received stats to Posthog as well.

Add posthog event for summary report

---

src/room/checkForParallelCalls.ts
src/room/useGroupCall.ts
test/room/checkForParallelCalls-test.ts

This is another KPI for PostHog.

Detect split-brains caused by parallel calls

---

package.json
yarn.lock

This PR depends on: https://github.com/matrix-org/matrix-js-sdk/pull/3301
This PR only updates the SDK with the new stat calculations.

Add new calculation of received media stats

---

src/otel/otel.ts
src/room/useGroupCall.ts

I'm not sure how this got left in, presumably it was not intended.

Remove the console exporter

---

src/otel/OTelGroupCallMembership.ts

Fixes https://github.com/vector-im/element-call/issues/1027

Include org.matrix.call events in sent events for OTel

---

src/Header.tsx
src/Modal.tsx
src/room/InviteModal.tsx
src/room/LobbyView.tsx
src/room/OverflowMenu.tsx
src/room/RoomAuthView.tsx

Hopefully the last batch of test id tags.
Only remaining ones might be required for managing audio rather than just video; but we'll cross that bridge when the adapter can play beeps.

Test tags for invite links; joining call by URL; getting call name.

---

src/analytics/PosthogSpanProcessor.ts
src/otel/otel.ts

depends on: https://github.com/matrix-org/matrix-js-sdk/pull/3349
Signed-off-by: Timo Kandra toger5@hotmail.de

add audio concealment to posthog exporter

---

src/room/InCallView.tsx

Makes reconnection testing practical (eg, client join/leaves 10 times; validate everything stays the same)

Add ability to explicitly hang up the call 

---

src/room/InCallView.tsx

Closes https://github.com/vector-im/element-call/issues/823

Hide the rageshake request modal when the window is too small

---

src/room/GroupCallView.tsx

As explained by the comment, we don't yet have designs that account for this combo.

Don't show the quality survey if the app is a widget

---

src/video-grid/VideoTile.tsx

this fixes both 
- the mirroring
- and screenshares beeing copped

screenshare live kit fix

---

package.json
src/matrix-utils.ts
yarn.lock

Use new-js-sdk flag to disable the actual calling of group calls

---

src/room/GroupCallView.tsx

This fixes an issue that was mentioned by @OmElDonia
(thanks @daniel-abramov )

"No device" crash

---

src/array-utils.ts
src/room/InCallView.tsx
src/video-grid/NewVideoGrid.module.css
src/video-grid/NewVideoGrid.tsx
src/video-grid/TileDescriptor.tsx
src/video-grid/model.ts
test/video-grid/model-test.ts

This improves how a few different common interactions affect the large grid. See the commits for details, and I recommend reviewing commit-by-commit

Improved large grid interactions

---

README.md
src/media-utils.ts
src/room/GroupCallView.tsx
src/widget.ts

By reinstating some of the code from the full mesh branch that was there to handle this

Fix device selection never completing in widget mode

---

src/analytics/PosthogAnalytics.ts
src/settings/submit-rageshake.ts

This is the full mesh branch counterpart to https://github.com/vector-im/element-call/pull/1136

Note the call backend in rageshake and analytics data

---

config/element_io_preview.json
src/UrlParams.ts
src/room/GroupCallView.tsx
src/widget.ts

This is related to: https://github.com/vector-im/voip-internal/issues/98 and need to be discuss!

Force to allow calls without video and audio in embedded mode
