src/settings/rageshake.js
This will stop groupcall.txt looking like it's a text log file and instead indicate it's an json artifact containing current state (which it is)
The file will still be stored on the rageshake server but the extension will indicate it's actually json data. We're already putting it in the "file" part of the rageshake, not the "logs" or "compressed-logs" parts, so it's already not meant to be handled as a log file.
(This is just a neatening up to make it easier to find the json data later)
=> Rename groupcall.txt -> groupcall.json.

src/room/PTTButton.jsx
Handle mouseup events anywhere so the button releases if you move
the cursor out of the button & release. Likewsie for window losing
focus.
=> Fix mouseup/down behaviour of PTT button

src/room/PTTButton.jsx, src/room/PTTCallView.jsx, src/room/usePTT.js
Based on https://github.com/vector-im/element-call/pull/311
Fixes https://github.com/vector-im/element-call/issues/297
=> Return to normal state when time limit reached

src/room/PTTButton.tsx, src/room/PTTCallView.module.css, src/room/PTTCallView.tsx
* Add touchstart / touchend events so the button is actually hold-to-speak on mobile
* Fix prompt text to not talk about spacebar on mobile (or at least, whenever there's a touchscreen).
* Move the complex ternary operator out into an if-statement before making it even more complex.
=> Fix hold-to-speak and prompt text on mobile

src/room/usePTT.ts
Play the 'blocked' sound effect whenever the user is till holding
the button but can't speak anymore, whether they've been cut off
by someone else or have reached their time limit.
=> Play the blocked sound on time limit

src/room/PTTButton.tsx
* Avoid also getting a 'mousedown' event by making the event listener
non-passive so the preventDefault() works
* Remember the touch that pressed the button so we only un-press
when that touch ends, otherwise the button gets released if the
user taps the screen anywhere else.
=> Fixes for touch interface on push-to-talk button

src/room/usePTT.ts
* Mute our own microphone if we're blocked from speaking by another user
* Serialise mute/unmute operations on a promise chain to fix races
Based on https://github.com/vector-im/element-call/pull/322
=> Mute local mic if blocked and fix races on mute / unmute

package.json, public/index.html, src/IndexedDBWorker.js, src/matrix-utils.js, yarn.lock
Depends on https://github.com/matrix-org/matrix-js-sdk/pull/2322
=> Add support for to-device messages via OLM

src/auth/LoginPage.jsx, src/auth/RegisterPage.jsx, src/auth/useInteractiveLogin.js, src/auth/useInteractiveRegistration.js, src/home/UnauthenticatedView.jsx, src/room/RoomAuthView.jsx
By waiting to set the client until after UnauthenticatedView has finished creating the room, we avoid both briefly flashing RegisteredView at the user, and potentially leaving the user stranded on RegisteredView without any indication of an error that occurred when creating the room.
Closes https://github.com/vector-im/element-call/issues/286.
=> Don't leave UnauthenticatedView if there was a room creation error

src/room/LobbyView.jsx
It was exploding on `roomId` being `undefined`.
=> Fix soft crash when opening invite modal in lobby

package.json, yarn.lock
Fixes https://github.com/vector-im/element-call/issues/257
=> Bump js-sdk dependency to encrypt to-device messages

src/video-grid/VideoGrid.jsx
Before|After
-|-
Closes https://github.com/vector-im/element-call/issues/240
Note that there are still many possible ways for video to get cropped, as that's inherent to the designs, but by limiting the width of the 1:1 layout, this should at least fix the most egregious case.
=> Limit the width of the remote participant's video in 1:1 layout

package.json, src/room/InCallView.jsx, src/video-grid/VideoGrid.jsx, yarn.lock
**Before**
https://user-images.githubusercontent.com/48614497/170128610-a7a2ece4-5223-471a-ba51-3cd96d827bf1.mp4
**After**
https://user-images.githubusercontent.com/48614497/170128639-7de002f0-59f8-4c83-ab69-316f8cb38eea.mp4
This is achieved by keeping the order of tiles in the DOM constant, and instead keeping track of an `order` key for each tile to determine which position it maps to.
Closes https://github.com/vector-im/element-call/issues/226
=> Smoother drag-and-drop

src/Menu.module.css, src/button/Button.jsx, src/button/Button.module.css, src/home/CallTypeDropdown.module.css, src/home/CallTypeDropdown.tsx, src/home/RegisteredView.jsx, src/home/UnauthenticatedView.jsx, src/index.css, src/room/GridLayoutMenu.jsx, src/room/GridLayoutMenu.module.css, src/useShouldShowPtt.js
Closes https://github.com/vector-im/element-call/issues/300
=> Add a dropdown to choose between video calls and radio calls

src/room/usePTT.ts
As hopefully explained by comment
For https://github.com/vector-im/element-call/issues/331
=> Sort call feeds consistently when choosing active speaker

src/auth/useInteractiveLogin.ts, src/auth/useInteractiveRegistration.ts, src/main.jsx
The recent typescripting appears to have caused the typescript
compiler to get confused about dependency references and start
refwrencing things like CRYPTO_ENABLED in the js-sdk before it's
defined them.
This avoids using things from the (javascript) browser-index import
and instead pulls everything in from the typescript files, then
fixes the resulting type failures, (in some cases with hacks).
Based on https://github.com/vector-im/element-call/pull/358
=> Fix app when built in production mode

src/main.tsx, src/room/InCallView.jsx
So that people are more likely to succeed at answering their own support questions like https://github.com/vector-im/element-call/issues/302
=> Produce a more informative error when running in an insecure context

src/room/PTTButton.tsx
We were using createRef() instead of useRef() in the hook, which
meant we were always creating a new ref object and never actually
getting the ref. This must have been working before the useEventTarget
stuff due to some quirk of React / hooks...
Fixes https://github.com/vector-im/element-call/issues/439
=> Fix the PTT button on mobile

package.json, src/matrix-utils.ts, yarn.lock
Deliberately not making it an option on the room since then we'd have to worry about server doing downgrade attacks.
Requires https://github.com/matrix-org/matrix-js-sdk/pull/2492
=> Add config param to disable e2e for signalling

src/room/PTTButton.module.css
Hopefully this matches what was intended (leaving it unset meant it didn't fill the whole height of the button.
Fixes https://github.com/vector-im/element-call/issues/445
=> Fix view when another person is talking

src/settings/SettingsModal.tsx
Fixes: #324
This isn't very elegant but at least prevents the empty dropdowns on Android. Possibly should move into `MediaHandlerProvider`? Open to feedback. 🙂
=> Prevent empty device labels

src/room/AudioPreview.jsx
Apply the fixes made in [#449](https://github.com/vector-im/element-call/pull/449) to audio preview component as well. Apologies, I missed that usage earlier.
Fixes: #324
=> Prevent empty device labels in audio preview

package.json, src/room/usePTT.ts, yarn.lock
The code was only entering the blocked state if the user was speaking,
which often won't be the case when another person starts speaking because
we'll have pressed the button but not got the ack back from the server
yet. Add the transmitblocked flag instead so we don't enter that state
again if we've already decided we've been blocked.
We were also starting with blocked = false and so resetting it when it
shouldn't have been reset.
Also requires https://github.com/matrix-org/matrix-js-sdk/pull/2502
=> Fix talking collision not colliding properly

src/Facepile.jsx, src/room/PTTCallView.module.css
Fixes https://github.com/vector-im/element-call/issues/434 and a
separate bug where the facepile would just disappear off to the left
(because we kept increasing the size even though we capped the number
of circles at 8 plus the overflow one).
=> Fix facepile display issues

src/ClientContext.tsx, src/auth/useInteractiveLogin.ts, src/auth/useInteractiveRegistration.ts, src/matrix-utils.ts
Add a check to ensure that we find crypto data in the crypto store
when we're restoring a session and otherwise abort the session restore.
This will prevent us from restoring a session and generating new keys
when there was a previous session with different keys.
***This will force a logout for all users***
See the linked issue (and the comment in code) for more detail.
Fixes https://github.com/vector-im/element-call/issues/464
=> Don't restore session unless crypto data is found

.vscode/settings.json
Apparently, without this, my VS Code still doesn't follow the rules
=> Be more explicit in `.vscode/settings.json`

src/home/RegisteredView.jsx, src/home/UnauthenticatedView.jsx, src/matrix-utils.ts, src/room/useLoadGroupCall.ts
We weren't waiting for rooms to arrive down the sync stream after
joining them but before trying to use them.
More regression details in linked issue.
Fixes https://github.com/vector-im/element-call/issues/477
=> Fix 'cannot find room' error

src/video-grid/useMediaStream.ts
Don't try to wire up audio nodes if the stream has no audio track,
'cos it'll crash.
Fixes https://github.com/vector-im/element-call/issues/421
=> Fix crash on screen share

src/App.jsx, src/FullScreenView.jsx, src/FullScreenView.module.css, src/main.tsx
We had an error boundary at the top level of the app, but it didn't
work because it used ErrorPage which tried to use a bunch of things
like useLocation() and an error prop. Also it wasn't passed in correctly
anyway.
This wires it up correctly to a separate view with a button to send
debug logs, and also moves it down a few layers so it has access to
enough things to be able to send rageshakes.
Related: https://github.com/vector-im/element-call/issues/421
=> Make the error boundary work

src/room/GroupCallInspector.tsx
`CallEvent.SendVoipEvent` is sent with a raw dictionary, not an actual `MatrixEvent`.
Closes https://github.com/matrix-org/matrix-video-chat-rageshakes/issues/1074
Closes https://github.com/matrix-org/matrix-video-chat-rageshakes/issues/1073
Closes https://github.com/matrix-org/matrix-video-chat-rageshakes/issues/1072
Closes https://github.com/matrix-org/matrix-video-chat-rageshakes/issues/1071
Closes https://github.com/matrix-org/matrix-video-chat-rageshakes/issues/1070
=> Fix a crash

src/room/VideoPreview.module.css
this reverts some of https://github.com/vector-im/element-call/commit/d1368f46220d36e6f76da24e0f08f78951f507de
it's very unclear why the width of the preview was pushed out to 100%+1px (and the transform then flipped to 1.01)
but i see no ill effects on having reverted it.
should fix https://github.com/vector-im/element-call/issues/392 and https://github.com/vector-im/element-call/issues/498
=> fix mirror text on FF by reverting weird css hack.

src/video-grid/useMediaStream.ts
The addition of an audio track wouldn't cause this hook to re-run. However, I don't think we should worry about optimizing for the case of 0 audio tracks at all, since that could only conceivably happen with screensharing feeds.
=> Fix a case where someone's audio could be missing if the audio track arrived late

src/room/GroupCallInspector.tsx, src/settings/submit-rageshake.ts
We were putting the whole array from setState in, so the debug info
was wrapped in an array when it shouldn't be.
Also comment the groupCallInspector setState/context dance which I
now *finally* understand.
=> Fix groupcall debug info in rageshakes

package.json, src/room/useLoadGroupCall.ts, yarn.lock
This (hopefully) fixes the remaining bug where extra group calls
could be created when entering a room.
We waited for the Room event to arrive, but didn't wait for the
group call event handler to actually process the event, so it would
have depended what order the event handlers were run in.
If this doesn't fix it, it at least adds logging so we'll have more
to go on next time.
Fixes https://github.com/vector-im/element-call/issues/563
=> Fix bug where additional group calls could be created

package.json, src/room/useLoadGroupCall.ts, yarn.lock
We were waiting for the group call event handler to process the room,
but only if we couldn't get the room from the client - if getRoom returned
a room, we just wouldn't wait. This just uses promises rather than
an event to wait for the room to be ready.
Looks like the failure was that we were getting a room from the store
and therefore not waiting for the event at all, but the fact that the room
was in the store doesn't mean it's been processed. We can't wait for
the event even if we got the room from the store because it may have
already happened in that case, so we'd be waiting forever for an event
that's already fired. Using promises fixes the race.
Requires https://github.com/matrix-org/matrix-js-sdk/pull/2641
=> Use new method to wait until a room is ready for group calls

src/room/useLoadGroupCall.ts
as otherwise it recurses and logs the entire client + store
=> Log ID instead of object

src/ClientContext.tsx, src/widget.ts
Element Web wants to keep two Element Call iframes in the DOM when switching between video rooms, and we have no reason to kill other sessions if the app is just a stateless widget (I think).
=> Don't kill other sessions when running as a widget

src/room/GroupCallView.tsx
Otherwise it can get stuck on screen in Element Web.
=> Unpersist widget after hanging up

package.json, tsconfig.json, yarn.lock
No CI checks at this time, the only effect this will have is adding IDE errors.
Closes https://github.com/vector-im/element-call/issues/558
=> Enable strict mode checks with typescript-strict-plugin

src/video-grid/VideoGrid.tsx
This was a confusion between indices of the tile and the tile position: the spotlight tile is the 0th TilePosition, ie. the tile with order 0, not the tile with index 0.
Also comment one method to hopefully make this slightly easier to understand.
Fixes https://github.com/vector-im/element-call/issues/499
=> Fix scroll bug in spotlight view

src/video-grid/VideoTile.tsx, src/video-grid/VideoTileContainer.tsx
This hides the toolbar and video tile settings modal as long as the active speaker is [maximised](https://github.com/vector-im/element-call/pull/581).
=> Further simplify the maximised speaker view

src/Tooltip.module.css, src/Tooltip.tsx
The only thing they're missing now is animated fading.
https://user-images.githubusercontent.com/48614497/192403117-90d9efab-78cb-4460-b4a1-3d35412254ed.mp4
Closes https://github.com/vector-im/element-call/issues/571
=> Make tooltips look more like Element Web's

src/room/InCallView.tsx
Closes https://github.com/vector-im/element-call/issues/591
=> Show a reduced set of controls when the window is narrow

src/media-utils.ts, src/room/GroupCallView.tsx
device IDs are different for each origin, so won't match up when passed in & out of widgets. Use the label instead.
For https://github.com/vector-im/element-web/issues/23331
=> Use device labels rather than IDs in widget API

src/video-grid/AudioContainer.tsx
Because to-device signaling can lag behind a user's actual audio, when you combine this with federation latency, you might end up cutting off the first few words of a user's sentence after they unmute.
I'd like to get this reviewed by @dbkr specifically before merging, to make sure this doesn't conflict with any walkie-talkie logic. (We did ultimately decide to leave feeds in walkie-talkie mode unmuted anyways, right?)
Closes https://github.com/vector-im/voip-internal/issues/63
=> Leave audio elements unmuted regardless of mute state

src/UrlParams.ts, src/room/InCallView.tsx
Signed-off-by: Šimon Brandner <simon.bra.ag@gmail.com>
=> Add `hideScreensharing` URL parameter

src/room/InCallView.tsx
Turns out `??` binds more tightly than `... ? ... : ...`
Closes https://github.com/vector-im/element-call/issues/624
=> Fix fullscreen buttons fullscreening the wrong feed

src/video-grid/VideoGrid.tsx
The code was previously confusing focused and presenter tiles quite a bit, and also had a couple different spots that would mistakenly engage 1:1 layout behavior when you're alone with your own screensharing feed.
This is a bit more easily explained with a video:
**Before**
https://user-images.githubusercontent.com/48614497/196336480-3005100d-b39a-4a79-91cc-5afe45a43c08.mp4
**After**
https://user-images.githubusercontent.com/48614497/196336477-4a159ca3-2237-445c-a73b-080afd112f25.mp4
=> Prevent screenshare feeds from collapsing when you're alone in freedom mode

src/media-utils.ts
The join handler was requesting a stream with both video and audio, even if the system lacked video or audio devices. Requesting one of audio or video is enough to get all device labels.
=> Fix joining calls in matryoshka mode without audio or video inputs

src/Facepile.tsx, src/room/InCallView.tsx
RoomWidgetClient doesn't do lazy loading, so it only has the state event data to work with and not the lazy loaded user object.
Previously avatars of remote participants were all replaced by fallback avatars.
=> Fix avatars of remote participants in matryoshka mode

.eslintrc.cjs, src/main.tsx
`ReactDOM.render` is deprecated in React 18, and was causing an error to be logged.
=> Switch to the React 18 createRoot API

package.json, src/App.tsx, src/matrix-utils.ts, src/olm.ts, test/mocks/olmMock.ts
React 18's strict mode intentionally mounts all components twice, which was causing Olm to get double-loaded. Also, it doesn't need to be loaded if the app is running as a widget.
=> Ensure that Olm is only loaded once

src/typography/Typography.module.css
This is in line with Element Web's behavior, and is a [WCAG accessibility requirement](https://webaim.org/techniques/hypertext/link_text#underlining).
=> Add an underline to blue (external) links on hover

src/room/useGroupCall.ts, src/video-grid/VideoGrid.tsx
The 'connecting' tile change meant that we could have tiles right at the start of the call where we wouldn't have before, and in fact could have tiles for other users before we even had a tile for ourself. This threw off the logic for ordering tiles which had a special case for 1:1 calling which assumed that one of the tiles in a 1:1 call was the local user. In this case, this assumption wasn't true at the very start of the call, so the tile orders got assigned incorrectly and then persisted for the rest of the call.
Fixes https://github.com/vector-im/element-call/issues/694
=> Fix missing tile bug

src/video-grid/VideoTile.tsx, src/video-grid/VideoTileContainer.tsx, src/video-grid/useAudioOutputDevice.ts, src/video-grid/useCallFeed.ts, src/video-grid/useMediaStream.ts
Because connecting tiles don't have a feed, clicking the local volume button would cause a soft crash. This also fixes a few strict mode errors in the surrounding area while we're at it.
=> Don't show toolbar buttons on connecting tiles

src/settings/useMediaHandler.tsx
We didn't check whether we actually had a video device when seeing if the current video devices was in the list of devices, so this caused loops which confused Safari.
Seems this was actually regressed by the latest Safari rather than any of our changes (it appears to emit a `devicechange` event after you get a stream to reflect the fact that you'll now get IDs and labels on your devices).
=> Fix Walkie-Talkie mode in Safari

src/room/InCallView.tsx, src/video-grid/VideoGrid.tsx
Because `useMeasure` always returns a width and height of zero on the first render, various call UI elements would flash in and out of existence or animate in from the wrong place when joining a call. This poses an accessibility issue, and is generally unpleasant.
Closes https://github.com/vector-im/element-call/issues/569
**Before**
https://user-images.githubusercontent.com/48614497/199638100-9ddd84e6-488c-46b0-8c4b-d98945ce0f78.mp4
**After**
https://user-images.githubusercontent.com/48614497/199638119-35acd0fa-b5c6-4cc3-86b6-e6cad0df9889.mp4
=> Improve the visual experience of joining a call

scripts/dockerbuild.sh
This build script might change more soon (we shouldn't really need to checkout & link the js-sdk at all) but for now let's just switch the branch now group-call is merged.
=> Don't check out group-call branch in build script

src/matrix-utils.ts
It said it was creating the room when actually it was creating the call
=> Make room / call creation logging more accurate

public/locales/en-GB/app.json, src/config/Config.ts, src/room/PTTButton.tsx, src/room/useGroupCall.ts, src/settings/SettingsModal.tsx, src/settings/useSetting.ts
I rely on using the `m` and `space` shortcuts to toggle mute in Jitsi all the time, and I *really* miss it.
I have *no* idea what I'm doing when it comes to react and javascript or whatever language I have just written, but it seems to work when I test it :shrug: 
Related issue: https://github.com/vector-im/element-call/issues/218
=> Add 'm' and 'space' shortcuts for mute/unmuting during a call

package.json, public/locales/en-GB/app.json, src/room/GroupCallView.tsx, src/room/InCallView.tsx, src/video-grid/VideoGrid.stories.tsx, src/video-grid/VideoTile.tsx, src/video-grid/VideoTileContainer.tsx, yarn.lock
This will show if the call is waiting for media to connect (in practice doesn't actually seem to happen all that often) but also show if the media connection is lost, with the js-sdk change.
Requires https://github.com/matrix-org/matrix-js-sdk/pull/2880
Fixes: https://github.com/vector-im/element-call/issues/669
=> Add a 'waiting for video' state to media tiles

src/ListBox.tsx
See comment, although this is quite hack - I'm torn on whether this is worth it for the bugfix. Upgrading react-aria doesn't fix it either (and also breaks everything in React strict mode).
Fixes https://github.com/vector-im/element-call/issues/762
=> Fix click leaking through to DOM element underneath

src/room/useLoadGroupCall.ts, src/widget.ts
In widget mode, it's the client's duty to start the call.
=> Don't start new calls in widget mode

scripts/dockerbuild.sh, vite.config.js
* We don't need to check out the js-sdk separately anymore
* Remove the vite proxying: there's no need since Matrix HSes allow cross origin requests. This will let us move the default homeserver config to the config file (in a separate PR...)
* Remove the product name variable which just set it to the default anyway
=> Simplify build process

package.json
It was in devDependencies as well as dependencies for some reason
=> Remove Olm from devDependencies

src/room/InCallView.tsx
It didn't work and fixing it is a bit of a project: see comment
https://github.com/vector-im/element-call/issues/807
=> Remove the overflow menu button in fullscreen mode

.github/workflows/build.yaml, .github/workflows/publish.yaml, Dockerfile, package.json, vite.config.js
Uses the vite sentry plugin which should also embed the release (in theory).
Also builds separately in the publish stage, as uploading source maps as part building the docker image is weird. This also means we can publish a tarball of just the built app.
Also fix the docker image again because I forgot to specify the destination file for the config file.
Secrets are added and should be ready to go.
=> Upload source maps to sentry

src/@types/global.d.ts, src/video-grid/useFullscreen.tsx
Safari only supports it via the webkit prefix
Fixes https://github.com/vector-im/element-call/issues/539
=> Fix fullscreen on Safari

src/PosthogAnalytics.ts, src/PosthogEvents.ts, src/room/GroupCallView.tsx
In embedded mode the iFrame will be killed right after the call ended. This prohibits the event from beeing sent. With the send_instantly flag we skip the posthog batching queue to send the event before the iFrame closes.
=> send posthog events instantly for callEnded in embedded mode

src/video-grid/VideoGrid.tsx
This resolves the last failure in https://github.com/vector-im/element-call/issues/787.
=> Reduce the size of the local feed in 1:1 calls at small window sizes

src/PosthogEvents.ts, src/room/useGroupCall.ts
This allows us to get insights about metrices like "mute events per call". And call size in relation to mute events...
=> Add call id to mute events

src/video-grid/VideoTile.tsx
A small optimization that I thought of: Since the app already determines when someone is speaking, we can use that information to make it less obvious when to-device messages are being slow to deliver mute state updates.
=> Work around mute state updates being slow

src/matrix-utils.ts
As per comment, we can't use workers in Vite dev mode. We previously fell back to the memory store but this ends up with it working significantly differently in dev mode to production, eg. dev mode would always start by doing an initial sync, so old to-device messages would arrive again.
There's no need to fall all the way back to the memory store though, we can use the IndexedDB store without the worker.
=> Use IndexedDB storage in dev mode, just without the worker

config/nginx.conf
Disable any caching other than etag based for everything other than the assets which have hash-based filenames.
Fixes https://github.com/vector-im/element-call/issues/840 (ie. this will avoid people being on different versions, unless they are super unlucky and different participants actually loaded the page before & after a deploy).
=> Fix caching headers on Docker image

package.json, src/PosthogAnalytics.ts, src/PosthogEvents.ts, src/room/GroupCallInspector.tsx, yarn.lock
Listen for the new undecryptable to-device event event and log events for it in Posthog & Sentry, and make it visible in the call flow diagram.
Requires https://github.com/matrix-org/matrix-js-sdk/pull/3066
=> Log undecryptable to-device events

src/matrix-utils.ts, src/room/useLoadGroupCall.ts
As per comment. This was breaking PTT embedding because it generated a mixed case room alias.
Also add a comment to an undocumented and very strange function.
=> Lowercase room alias before joining

src/room/useLoadGroupCall.ts
We use this in embedded mode. Regressed by https://github.com/vector-im/element-call/pull/860
Lowercasing room IDs obviously makes them break, so… don't do that.
=> Fix joining rooms by ID

src/room/PTTCallView.tsx
As per comment
Unsure if this is the best fix - ideally we wouldn't go into no-controls mode at all, but this part doesn't know whether the dialog is open so the only thing we could really do is tweak the threshold, or possibly guess based on width instead?
Fixes https://github.com/vector-im/element-call/issues/868
=> Fix the rageshake modal on mobile

README.md
Updated README.md to include more detailed information about the limitations of Element Call and a recommended homeserver set up.
The reason for this update is that as a random person trying to self-host Element Call, I struggled to figure out how it works in relation to the HS it uses, and took some time to figure out it does not work unless open registration is enabled (which is generally bad practice, so I also eventually noticed the public instance at call.element.io uses a separate HS which is not federated).
I included my findings in the README so others trying to self-host have a clearer picture of the app's inner workings and particularities.
=> Be more clear about homeserver requirements in README.md

src/room/useGroupCall.ts
This adds handlers for the media actions to do nothing, otherwise they cause the audio element for a random participant to get paused.
Fixes https://github.com/vector-im/element-call/issues/855
=> Don't pause audio streams on media actions

src/widget.ts
Allow to-device signaling in matryoshka mode to be unencrypted, like in the standalone client. This is useful especially for testing and also for clients which do not yet support encryption, like Quadrix. The default value for the optional `e2eEnabled` URL parameter is "true", so this should not have any impact on existing implementations using the matrix-widget-api, like Element Web.
I have tested this commit in a test build of Quadrix, at: https://github.com/alariej/quadrix/blob/7f134a3646932e3d4d92538ade1e6a63cc94fd5c/src/modules/ElementCall/index.tsx#L314
=> Add e2eEnabled parameter to Widget client

package.json, yarn.lock
Update `matrix-js-sdk` for the `GroupCall` fix:
- Because ensure group call backwards-compatibility the `CroupCall` constructor hast to be changed
- Please compare here: https://github.com/matrix-org/matrix-js-sdk/commit/8cbbdaa239e449848e8874f041ef1879c1956696
- Related to #902
=> Update matrix-js-sdk to get GroupCall Fix

src/analytics/OtelPosthogExporter.ts, src/analytics/PosthogAnalytics.ts
Call rejoins will be one of the KPIs we track in PostHog to measure call quality. I've also reverted the previous behavior which logged all OpenTelemetry spans to PostHog, since we should only be sending small, anonymized bits of data there.
=> Track call rejoins

src/ClientContext.tsx, src/analytics/PosthogAnalytics.ts, src/otel/OTelGroupCallMembership.ts
PostHog was expecting the matrix client object to be initialised at the point it ran its setup, which wasn't the case. Check to see if it's there on login and add an onLoginStatusChanged hook that to re-check.
Also make a few methods private that didn't need to be public.
Also fix a few instances where the OpenTelemetry group call tried to report metrics using a tracer which didn't exist anymore, if the user disabled analytics and then joined the same call again.
=> Fix exception when loading PostHog

src/analytics/OtelPosthogExporter.ts, src/analytics/RageshakeSpanExporter.ts, src/otel/otel.ts, src/settings/submit-rageshake.ts
This attaches OpenTelemetry traces to rageshakes as a gzipped file named 'traces.json', which, after unzipping, can be loaded directly into analysis tools like Jaeger or Stalk.
The file name is a little unfortunate—if I change it to 'traces.json.gz' then our rageshake server seems to reject it. I tried setting an explicit content type on the blob, but that didn't seem to work, so I could use ideas here.
There's another important caveat: Since exporters only receive spans after they've been ended, this currently won't attach any useful telemetry if you submit a rageshake in the middle of a call. I suggest we get this merged as a first iteration, and then figure out how to work around that.
=> Include OpenTelemetry traces in rageshakes

src/otel/OTelGroupCallMembership.ts
Since `typeof null` is `'object'`, the `flattenVoipEventRecursive` function was mistakenly casting nulls to `Record<string, unknown>` in its `typeof v === "object"` case, causing `Object.entries` to explode.
Closes https://github.com/vector-im/element-call/issues/993
=> Fix a crash when adding call events to telemetry

package.json, test/otel/ObjectFlattener-test.ts, yarn.lock
The current develop branch [matrix-js-sdk](https://github.com/matrix-org/matrix-js-sdk/pull/3270)  contains jitter in the stats
=> Add jitter in webrtc stats

src/analytics/RageshakeSpanProcessor.ts, src/otel/otel.ts, src/settings/submit-rageshake.ts
By turning the RageshakeSpanExporter into a SpanProcessor, it can now be notified of spans as soon as they're started.
=> Include unended spans in rageshakes

src/room/GroupCallView.tsx
Embedded mode has a differtent path to join the call and we missed changing the groupCall.enter() function for the wrapper that does analytics.
=> Fix PostHog in embedded mode

src/analytics/RageshakeSpanProcessor.ts
Fixes times being off by a factor of 1000
=> Use microseconds in the rageshake exporter

src/settings/submit-rageshake.ts
As we are sending a gzipped file. This will make the rageshake server gunzip it when it serves it: https://github.com/matrix-org/rageshake/blob/master/logserver.go#L90
=> Add .gz extension to to traces.json

src/settings/submit-rageshake.ts
Reverts vector-im/element-call#1016
It turns out this actually doesn't work.
=> Revert "Add .gz extension to to traces.json"

src/video-grid/VideoGrid.tsx
My dev env suddenly, with no apparent prompt, went into a mode where it wouldn't display nay video tiles which was because they were 0x0 in the top left corner, which in turn was because the ResizeObserver was never returning the actual bounds of the video tile container.
As per comment, this uses the native impl in preference to the ponyfill, although in practice it looks like all our target browsers should support it, so perhaps we could just remove the ponyfill entirely.
=> Use the native ResizeObserver where available

public/locales/en-GB/app.json, src/room/InCallView.tsx, src/settings/SettingsModal.tsx, src/settings/useSetting.ts, src/useCallViewKeyboardShortcuts.ts
This changes keyboard shortcuts to only take effect when the call controls are in the same part of the tree that's focused, which seems to work well enough that we can now remove the keyboard shortcuts setting (which was just an accessibility kludge).
Closes https://github.com/vector-im/element-call/issues/888
Closes https://github.com/vector-im/element-call/issues/757
=> Make keyboard shortcuts accessible by default

src/room/InCallView.module.css, src/room/InCallView.tsx
Before:
After:
Closes https://github.com/vector-im/element-call/issues/954
=> Keep inspector from covering call buttons

src/useCallViewKeyboardShortcuts.ts
https://github.com/vector-im/element-call/pull/1015/files missed a change of spacebarHeld to a ref.
=> Fix audio mute on window blur

src/settings/submit-rageshake.ts
Re-applies vector-im/element-call#1016
This actually works on the server now.
=> Re-apply "Add .gz extension to to traces.json"

src/UserMenu.tsx, src/auth/LoginPage.tsx, src/auth/RegisterPage.tsx, src/home/RegisteredView.tsx, src/home/UnauthenticatedView.tsx, src/profile/ProfileModal.tsx
Adding more test IDs for various other bits of UI.
Currently not good to merge; I'm having issues understanding how to extend Item to render test IDs, it doesn't seem to be doing so in the same manner as other elements are, but i wanted to put it up to ask questions about it.
=> Add data-testid tags for registration, login, displayname & logout

src/video-grid/VideoTile.module.css
A light touch of animation here is consistent with what the designs call for, and what we've done with the toolbars on video tiles.
=> Subtly animate active speaker indicators

src/video-grid/VideoTile.module.css, src/video-grid/VideoTile.tsx
Previously we were showing a combination of audio and video status icons on people's name badges, which meant there was no way to tell whether someone who had their video off was muted or not. The designs call for only microphone icons to be shown here.
=> Show audio mute status next to people's names

src/video-grid/NewVideoGrid.tsx, src/video-grid/VideoGrid.tsx, src/video-grid/VideoTile.module.css, src/video-grid/VideoTile.tsx, src/video-grid/VideoTileContainer.tsx
So that the local tile in 1:1 calls is more discernable against the background, especially when both participants have their video off
=> Use a more noticeable shadow when displaying one tile on top another

src/video-grid/VideoGrid.tsx
So that it doesn't cover up too much of the remote tile at small window sizes
Closes https://github.com/vector-im/element-call/issues/1039
=> Cap the size of the local tile in 1:1 calls

src/media-utils.ts, src/room/GroupCallView.tsx, src/settings/SettingsModal.tsx, src/settings/useMediaHandler.tsx
This one is gonna take some explaining:
When in resist fingerprinting mode, Firefox exhibits some funny behavior: when we ask for the the list of media devices, it gives us fake device IDs. But when the js-sdk requests a stream for any of those devices, Firefox associates the stream with the real device ID.
Now, in order to get the names of devices included in their metadata when you query the device list, you need to be holding a stream. For this reason, `useMediaHandler` was set up to reload the device list whenever matrix-js-sdk got a new local stream. But because of the inconsistency in device IDs, it would enter an infinite cycle telling matrix-js-sdk to request a stream for the fake device ID, but with matrix-js-sdk always responding with the real device ID.
I already wasn't happy …
=> Make Element Call work in Firefox's resist fingerprinting mode

src/analytics/PosthogSpanProcessor.ts
fixes: https://github.com/vector-im/voip-internal/issues/156
requires: https://github.com/matrix-org/matrix-js-sdk/pull/3424
=> Add splitbrain paremeters to MediaReceived event

src/room/useGroupCall.ts
In `GroupCallView` we do `await enter()` when responding to a widget API join request, but it turns out `enter` wasn't actually returning a promise until now. The consequence of this was that in Element Web, when you click the join button you get shown a blank screen for a moment. This fixes that half-second moment of the UI being broken, allowing Element Web to show the intermediate 'joining' state.
=> Don't prematurely claim that we've joined the call in widget mode

src/video-grid/NewVideoGrid.tsx
The new grid layout has been broken ever since upgrading react-spring, because it was apparently relying on a buggy behavior of react-spring that started transitions automatically even in imperative mode. react-spring 9.5.1 fixed that behavior, which means we now need to manually start the animations.
=> Fix tiles not animating in the new grid layout

src/room/CallEndedView.tsx
We want to encourage scoring as much as possible for the purpose of our KPIs, even if it means we don't always get detailed textual feedback.
=> Don't require textual feedback

src/video-grid/VideoTile.tsx
This fixes a couple bugs:
1. That muting your video while screensharing would cause the screensharing feed to be hidden as well
2. That while screensharing, your user media tile would incorrectly show the label that's supposed to appear only on the screenshare tile
=> Fix tiles having the wrong states during screensharing

src/room/InCallView.tsx, src/video-grid/VideoTile.tsx
This fixes two edge cases:
- Screenshares should never have a speaking indicator
- Speaking indicators should be hidden in 1:1 calls
=> Fix speaking indicators showing up when they shouldn't

src/video-grid/NewVideoGrid.tsx
By only updating the one spring of the tile that's being interacted with
=> Improve the performance of dragging tiles in the large grid

public/locales/en-GB/app.json, src/room/InCallView.tsx, src/settings/SettingsModal.tsx, src/settings/useSetting.ts, src/video-grid/VideoTile.tsx
Calls are an environment with high cognitive load, so it's important that we keep extra UI elements like these to a minimum and stick to what's been explicitly designed. I assume that this was here as a developer feature to diagnose reliability of the back end components, which is perfectly fine, so I've kept it behind a developer setting rather than fully removing it.
=> Hide connection quality indicators behind a developer setting

src/video-grid/VideoGrid.tsx, src/video-grid/VideoTile.tsx
Because the local user is always first in the list of participants, the local user always gets the order 0. That's why the local user after joined is in the spotlight. The local user should never be in the spotlight.  This is a fix for it.
=> Local user should never be in the spotlight

.github/workflows/test.yaml, package.json
https://app.codecov.io/gh/vector-im/element-call/tree/michaelk%2Freport_coverage/src for demonstration that the output works.
The comment from codecov in this PR is errorful because we haven't run this on main yet so there's no difference available.
=> Push code coverage percentages to codecov.io.
